name: powerpc port

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install packages
      run: tools/ci.sh powerpc_setup
    - name: Build
      run: tools/ci.sh powerpc_build
